/**
 * ESLint configuration for Simple Taxonomy Refreshed.
 *
 * Extends the default @wordpress/scripts flat config with two project specifics:
 *  - Blocks import WordPress packages that webpack externalises to `wp.*`, so they are
 *    never installed in node_modules. Treat them as core modules.
 *  - src/common/*.js are classic (non-module) scripts. Their snake_case functions are
 *    called from inline scripts generated by PHP, so they are globals by design.
 */
const defaultConfig = require( '@wordpress/scripts/config/eslint.config.cjs' );

module.exports = [
	...defaultConfig,
	{
		files: [ 'src/blocks/**/*.js' ],
		settings: {
			'import/core-modules': [
				'@wordpress/block-editor',
				'@wordpress/blocks',
				'@wordpress/components',
				'@wordpress/core-data',
				'@wordpress/data',
				'@wordpress/editor',
				'@wordpress/element',
				'@wordpress/i18n',
				'@wordpress/server-side-render',
			],
		},
	},
	{
		files: [ 'src/common/**/*.js' ],
		languageOptions: {
			sourceType: 'script',
			globals: {
				MutationObserver: 'readonly',
			},
		},
		rules: {
			// Function names form the PHP <-> JS interface; renaming them would break the inline scripts.
			camelcase: 'off',
		},
	},
];
