#!/bin/sh

set -e

export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$HOME/.composer/vendor/squizlabs/php_codesniffer/bin:$PATH"

SNIFF=$TRAVIS_BUILD_DIR/vendor

echo $TRAVIS_BUILD_DIR/vendor/bin
ls -lt $TRAVIS_BUILD_DIR/vendor/bin

echo $HOME
ls -lt $HOME

phpcs --config-set installed_paths $SNIFF/wp-coding-standards/wpcs,$SNIFF/phpcompatibility/phpcompatibility-wp,$SNIFF/phpcompatibility/php-compatibility,$SNIFF/phpcompatibility/phpcompatibility-paragonie
phpcs --config-show

phpcs --standard=phpcs.ruleset.xml -p -s --colors *.php */**.php -v

ls -lt $HOME

ls -lt $HOME/.composer/vendor

ls -lt $HOME/.composer/vendor/squizlabs/php_codesniffer/bin
